"""Add role id to user table

Revision ID: 485da13da336
Revises: 25b97ba36aa6
Create Date: 2024-03-12 20:57:34.617121

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '485da13da336'
down_revision: Union[str, None] = '25b97ba36aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'timestamp',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.alter_column('user', 'registered_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'registered_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.drop_column('user', 'role_id')
    op.alter_column('rating', 'timestamp',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    # ### end Alembic commands ###
