services:
  sign_classifier:
    build: sign_classifier
    ports: 
      - "80:80"
    volumes:
    - ./sign_classifier/models:/models
    - ./sign_classifier/app:/code/app
     
  tg_bot:
    build: tg_bot
    depends_on:
      - sign_classifier
    volumes:
    - ./tg_bot:/bot