FROM python:3.10-bullseye

WORKDIR /code

RUN apt-get update \
    && apt-get install netcat ffmpeg libsm6 libxext6 -y

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

RUN pip install --no-cache-dir jinja2

# VOLUME [ "sign_classifier/models:sign_classifier/models:rw" ]

# COPY ./app /code/app
# EXPOSE 80

ADD docker.sh /
RUN chmod +x /docker.sh

CMD ["/docker.sh"]