FROM python:3.10-bullseye

WORKDIR /code

RUN apt-get update \
    && apt-get install ffmpeg libsm6 libxext6 -y

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# VOLUME [ "sign_classifier/models:sign_classifier/models:rw" ]

# COPY ./app /code/app
# EXPOSE 80

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--log-config", "app/log_conf.yaml"]